# Generated by Django 5.1.4 on 2026-07-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Electronics", "Electronics"),
                            ("Furniture", "Furniture"),
                            ("Textbooks", "Textbooks"),
                            ("Clothing", "Clothing"),
                            ("Hostel Essentials", "Hostel Essentials"),
                            ("Kitchen Appliances", "Kitchen Appliances"),
                            ("Accessories", "Accessories"),
                            ("Stationery", "Stationery"),
                            ("Sports", "Sports"),
                        ],
                        max_length=30,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "condition",
                    models.CharField(
                        choices=[("New", "New"), ("Used", "Used")],
                        default="Used",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
